### ISSUE TITLE
Can't bundle gallop with rollup/esbuild

### ISSUE THREAD

**Issue by gluck** [tarnishablec/gallop#30]
Hi, latest gallop is failing on webcomponents.dev:
https://webcomponents.dev/edit/CToseUd2lyE37ySs7Tsk/src/index.ts

This is caused by package.json exports entry, which points to non-existing `./src/index.ts` for ESM bundling:
https://github.com/tarnishablec/gallop/blob/master/packages/gallop/package.json#L7-L10

Although there's another (existing) entry in the array, no bundler even try it, because the node resolve algorithm doesn't fallback on non-existing files:
- Spec: https://nodejs.org/api/esm.html#esm_resolver_algorithm_specification
- Implemented verbatim in `@rollup/plugin-node-resolve`: https://github.com/rollup/plugins/blob/00e16d9ef314ae252ed7ecaf429097675a107352/packages/node-resolve/src/package/resolvePackageTarget.js#L6

Thanks.

**Comment by tarnishablec** [comment]
Yes! You are right, I found that "exports" field should be removed, a new patch was released, Thanks!
